package com.khushitshah.blindspartner.libs.Utils;

public enum TypesOfSentences {
    TYPE_VIDEO_PROCESSED,
    TYPE_NOT_KNOWN_COMMAND,
    TYPE_CALL_CONFIRM,
    TYPE_MESSAGE_CONFIRM,
    TYPE_MESSAGE_ASK_CONTENT,
    TYPE_SOS_MSG_INFORM,
    TYPE_LOCATION,
    TYPE_FETCHING,
    TYPE_CANT_FETCH,
    TYPE_HELP,
    TYPE_NOTIFICATION,
    TYPE_SOS_MSG_INFORM2,
    TYPE_IMAGE_PROCESSED_NO_OBJECTS,
    TYPE_CALL_MESSAGE_CANCEL,
    TYPE_STOP,
    TYPE_TIME,
    TYPE_NEWS,
    TYPE_CANT_FOUND_NUMBER,
    TYPE_MULTIPLE_CONTACTS,
    TYPE_IMAGE_PROCESSED_SINGLE_OBJECT, TYPE_CREDITS,
    TYPE_TEST
}
